#!/usr/bin/env bun
/**
 * sync-abis — extract ABIs from forge `out/` artifacts into
 * `packages/core/src/abis/` so the SDK ships with no Foundry dependency.
 *
 * Run from the repo root: `bun run sdk/scripts/sync-abis.ts`
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = join(__dirname, "..", "..");
const OUT_DIR = join(REPO_ROOT, "out");
const ABI_DIR = join(REPO_ROOT, "sdk", "packages", "core", "src", "abis");

/** Contracts whose ABIs the SDK consumes. Keep this list narrow; any ABI we
 *  don't actually use shouldn't ship to keep the bundle lean. */
const CONTRACTS = [
  "ACLIdentityRegistry",
  "ACLReputationRegistry",
  "ACLValidationRegistry",
  "ACLOffchainResolver",
  "ACLEvaluator",
  "AgenticCommerce",
  "ACLTestUSDC",
  "ACLAgentNFT",
] as const;

/**
 * Hand-written ABIs that live alongside the generated ones. The sync
 * script never overwrites them — it only re-exports them from
 * `abis/index.ts` so consumers get a single import surface.
 */
const HAND_WRITTEN_ABIS: readonly { file: string; varName: string }[] = [
  { file: "IERC20", varName: "ierc20Abi" },
];

type Contract = (typeof CONTRACTS)[number];

function readAbi(name: Contract): unknown[] {
  const artifactPath = join(OUT_DIR, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    throw new Error(`Forge artifact not found: ${artifactPath}\nRun \`forge build\` first.`);
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as {
    abi: unknown[];
  };
  return artifact.abi;
}

function camelCase(name: string): string {
  // "ACLIdentityRegistry" → "aclIdentityRegistry" (lowercase the leading
  // run of consecutive uppercase letters, except keep the last one if the
  // next char is lowercase: "AbiCoder" → "abiCoder").
  let i = 0;
  while (
    i < name.length &&
    name[i] === name[i]?.toUpperCase() &&
    name[i] !== name[i]?.toLowerCase()
  ) {
    i++;
  }
  if (i <= 1) return name.charAt(0).toLowerCase() + name.slice(1);
  // Keep the last uppercase letter if it starts a new word.
  if (i < name.length) i -= 1;
  return name.slice(0, i).toLowerCase() + name.slice(i);
}

function main(): void {
  mkdirSync(ABI_DIR, { recursive: true });

  const indexLines: string[] = [
    "/* AUTO-GENERATED by sdk/scripts/sync-abis.ts. Do not edit by hand. */",
    "",
  ];

  for (const name of CONTRACTS) {
    const abi = readAbi(name);
    const file = join(ABI_DIR, `${name}.ts`);
    const varName = `${camelCase(name)}Abi`;
    writeFileSync(
      file,
      `/* AUTO-GENERATED. Source: out/${name}.sol/${name}.json */\nexport const ${varName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
    );
    indexLines.push(`export { ${varName} } from './${name}.js';`);
  }

  // Re-export hand-written ABIs (e.g. IERC20) so consumers get a
  // single import surface from `@acl/core/abis`.
  if (HAND_WRITTEN_ABIS.length > 0) {
    indexLines.push("");
    indexLines.push("// Hand-written ABIs — not regenerated by sync-abis.");
    for (const entry of HAND_WRITTEN_ABIS) {
      const handPath = join(ABI_DIR, `${entry.file}.ts`);
      if (!existsSync(handPath)) {
        throw new Error(
          `Hand-written ABI declared in HAND_WRITTEN_ABIS is missing on disk: ${handPath}`,
        );
      }
      indexLines.push(`export { ${entry.varName} } from './${entry.file}.js';`);
    }
  }

  writeFileSync(join(ABI_DIR, "index.ts"), `${indexLines.join("\n")}\n`);

  // JSON.stringify always emits double quotes; run biome so the generated
  // files match the project style and `bun run lint` stays clean.
  const sdkDir = join(REPO_ROOT, "sdk");
  const target = relative(sdkDir, ABI_DIR);
  spawnSync("bunx", ["biome", "format", "--write", target], {
    cwd: sdkDir,
    stdio: "inherit",
  });
  console.log(`Synced ${CONTRACTS.length} ABIs into ${ABI_DIR}`);
}

main();
